name: EMBA default installation on Ubuntu

on:
  schedule:
    - cron: '0 0 * * */2' # do it every 2nd day
#  push:
#    branches:
#      - '**'        # matches every branch
#  pull_request:
#    branches:
#      - '**'
#  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  default-install:
    # if: github.repository_owner == 'e-m-b-a'
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          swap-storage: true
      - name: EMBA default install
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 800
          max_attempts: 3
          command: |
            sudo rm -r ./external || true
            sudo ./installer.sh -g
            NO_UPDATE_CHECK=1 sudo -E ./emba -d 1 -y
      - name: EMBA firmware download
        run: |
            sudo apt-get update
            sudo apt-get install wget
            wget https://ftp.dlink.de/dir/dir-300/archive/driver_software/DIR-300_fw_revb_214b01_ALL_de_20130206.zip
      - name: EMBA default analysis
        run: |
            NO_UPDATE_CHECK=1 sudo -E ./emba -f ./DIR-300_fw_revb_214b01_ALL_de_20130206.zip -l ./logs_emba -S -p ./scan-profiles/default-scan.emba -y
      - name: Check result files exist
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "./logs_emba/emba.log, ./logs_emba/csv_logs/f50_base_aggregator.csv, ./logs_emba/html-report/index.html"

      - name: Files exist
        if: steps.check_files.outputs.files_exists == 'true'
        # Only runs if all of the files exist
        run: echo All files exist!
