name: Update Linux Kernel version database

on:
  schedule:
    - cron: '0 0 * * 0' # do it every week
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update_kernel_db:
    if: github.repository_owner == 'e-m-b-a'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v3
    - name: Install requirements
      run: |
        sudo apt-get update -y
        sudo apt-get install curl -y
    - name: update Linux kernel version db
      run: |
        ./helpers/generate_kernel_info.sh || exit 1
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update Linux kernel version database
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: gcc_update
        delete-branch: true
        title: 'Linux kernel version database update'
        body: |
          Update report
          - Updated latest Linux kernel version details
        labels: |
          db_update
          automated pr
        milestone: 0
        draft: false
